# 项目相关配置
iot:
  # 名称
  name: IotCloud
  # 版本
  version: 1.1
  # 版权年份
  copyrightYear: 2023

# 开发环境配置
spring:
  application:
    name: iot-clouds
  profiles:
    active: prod
      
jwt:
  tokenHeader: Authorization
  secret: exam-secret
  expiration: 604800
  tokenHead: 'Bearer '